package com.udea.skadysystem.persistencia;
// Generated 4/06/2017 08:00:08 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoPaleta generated by hbm2java
 */
@Entity
@Table(name="tipo_paleta"
    ,catalog="skady"
)
public class TipoPaleta  implements java.io.Serializable {


     private Integer codigo;
     private String nombre;

    public TipoPaleta() {
    }

    public TipoPaleta(String nombre) {
       this.nombre = nombre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CODIGO", unique=true, nullable=false)
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="NOMBRE", length=10)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


