package com.udea.skadysystem.persistencia;
// Generated 4/06/2017 08:00:08 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="skady"
)
public class Usuario  implements java.io.Serializable {


     private Integer gv_id;
     private String gv_nombre;
     private String gv_cedula;
     private String gv_password;
     private String gv_telefono;
     private String gv_celular;
     private Integer gv_sede;

    public Usuario() {
    }

	
    public Usuario(String nombre, String cedula, String password, String telefono, String celular) {
        this.gv_nombre = nombre;
        this.gv_cedula = cedula;
        this.gv_password = password;
        this.gv_telefono = telefono;
        this.gv_celular = celular;
    }
    public Usuario(String nombre, String cedula, String password, String telefono, String celular, Integer sede) {
       this.gv_nombre = nombre;
       this.gv_cedula = cedula;
       this.gv_password = password;
       this.gv_telefono = telefono;
       this.gv_celular = celular;
       this.gv_sede = sede;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.gv_id;
    }
    
    public void setId(Integer id) {
        this.gv_id = id;
    }

    
    @Column(name="NOMBRE", nullable=false, length=40)
    public String getNombre() {
        return this.gv_nombre;
    }
    
    public void setNombre(String nombre) {
        this.gv_nombre = nombre;
    }

    
    @Column(name="CEDULA", nullable=false, length=10)
    public String getCedula() {
        return this.gv_cedula;
    }
    
    public void setCedula(String cedula) {
        this.gv_cedula = cedula;
    }

    
    @Column(name="PASSWORD", nullable=false, length=20)
    public String getPassword() {
        return this.gv_password;
    }
    
    public void setPassword(String password) {
        this.gv_password = password;
    }

    
    @Column(name="TELEFONO", nullable=false, length=10)
    public String getTelefono() {
        return this.gv_telefono;
    }
    
    public void setTelefono(String telefono) {
        this.gv_telefono = telefono;
    }

    
    @Column(name="CELULAR", nullable=false, length=10)
    public String getCelular() {
        return this.gv_celular;
    }
    
    public void setCelular(String celular) {
        this.gv_celular = celular;
    }

    
    @Column(name="SEDE")
    public Integer getSede() {
        return this.gv_sede;
    }
    
    public void setSede(Integer sede) {
        this.gv_sede = sede;
    }




}


