package com.udea.skadysystem.persistencia;
// Generated 4/06/2017 08:00:08 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VentaProducto generated by hbm2java
 */
@Entity
@Table(name="venta_producto"
    ,catalog="skady"
)
public class VentaProducto  implements java.io.Serializable {


     private Integer gv_id;
     private int gv_codigoVenta;
     private String gv_nombre;
     private int gv_codigo;
     private int gv_cantidad;
     private double gv_precio;

    public VentaProducto() {
    }

    public VentaProducto(int codigoVenta, String nombre, int codigo, int cantidad, double precio) {
       this.gv_codigoVenta = codigoVenta;
       this.gv_nombre = nombre;
       this.gv_codigo = codigo;
       this.gv_cantidad = cantidad;
       this.gv_precio = precio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.gv_id;
    }
    
    public void setId(Integer id) {
        this.gv_id = id;
    }

    
    @Column(name="CODIGO_VENTA", nullable=false)
    public int getCodigoVenta() {
        return this.gv_codigoVenta;
    }
    
    public void setCodigoVenta(int codigoVenta) {
        this.gv_codigoVenta = codigoVenta;
    }

    
    @Column(name="NOMBRE", nullable=false, length=20)
    public String getNombre() {
        return this.gv_nombre;
    }
    
    public void setNombre(String nombre) {
        this.gv_nombre = nombre;
    }

    
    @Column(name="CODIGO", nullable=false)
    public int getCodigo() {
        return this.gv_codigo;
    }
    
    public void setCodigo(int codigo) {
        this.gv_codigo = codigo;
    }

    
    @Column(name="CANTIDAD", nullable=false)
    public int getCantidad() {
        return this.gv_cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.gv_cantidad = cantidad;
    }

    
    @Column(name="PRECIO", nullable=false, precision=22, scale=0)
    public double getPrecio() {
        return this.gv_precio;
    }
    
    public void setPrecio(double precio) {
        this.gv_precio = precio;
    }




}


