package com.udea.skadysystem.persistencia;
// Generated 4/06/2017 08:00:08 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VentaProducto generated by hbm2java
 */
@Entity
@Table(name="venta_producto"
    ,catalog="skady"
)
public class VentaProducto  implements java.io.Serializable {


     private Integer id;
     private int codigoVenta;
     private String nombre;
     private int codigo;
     private int cantidad;
     private double precio;

    public VentaProducto() {
    }

    public VentaProducto(int codigoVenta, String nombre, int codigo, int cantidad, double precio) {
       this.codigoVenta = codigoVenta;
       this.nombre = nombre;
       this.codigo = codigo;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="CODIGO_VENTA", nullable=false)
    public int getCodigoVenta() {
        return this.codigoVenta;
    }
    
    public void setCodigoVenta(int codigoVenta) {
        this.codigoVenta = codigoVenta;
    }

    
    @Column(name="NOMBRE", nullable=false, length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="CODIGO", nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="CANTIDAD", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="PRECIO", nullable=false, precision=22, scale=0)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }




}


